import OpenAI from "openai";
import { db } from './db';
import { courses, modules, lessons, lessonContentBlocks, courseCategories } from '../shared/schema';
import { eq } from 'drizzle-orm';
import { ensureAdminUser } from './ensure-admin-user';
import { CloudflareR2Storage } from './cloudflare-r2-storage';
import https from 'https';
import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const r2Storage = new CloudflareR2Storage();

const COURSE_TITLE = 'Job Readiness and Career Success';

const COURSE_STRUCTURE = {
  course_id: "job_readiness_career_success_v1",
  title: "Job Readiness and Career Success",
  tagline: "Comprehensive training for employment success",
  level: "beginner",
  description: "A comprehensive course that teaches the fundamentals of job readiness, career planning, resume building, interview skills, workplace success, communication, and financial awareness. Perfect for anyone preparing to enter or re-enter the workforce.",
  learning_outcomes: [
    "Understand job readiness skills and employer expectations",
    "Develop self-assessment and career planning abilities",
    "Create professional resumes and applications",
    "Master interview preparation and communication",
    "Build workplace success habits and relationships",
    "Understand workplace rights and financial basics"
  ]
};

interface LessonData {
  lesson_id: string;
  title: string;
  body: string;
  images: { image_id: string; prompt: string }[];
}

interface ModuleData {
  module_id: string;
  title: string;
  lessons: LessonData[];
}

const MODULES_DATA: ModuleData[] = [
  {
    module_id: "M1",
    title: "Understanding Job Readiness and Career Foundations",
    lessons: [
      { lesson_id: "M1L1", title: "What Job Readiness Means", body: "Job readiness refers to the combination of skills, behaviors, knowledge, and attitudes that prepare a person to enter and succeed in the workplace. It is not only about having technical skills but also about being dependable, professional, and adaptable. Employers look for individuals who are prepared to work responsibly, communicate clearly, and handle tasks effectively.\n\nJob readiness begins with understanding expectations. Every workplace has rules, routines, and standards. Being ready for work means knowing how to follow instructions, respect time schedules, and complete tasks as expected. It also includes being prepared mentally and emotionally to work with others.\n\nAnother key part of job readiness is self-awareness. Understanding personal strengths and areas for improvement helps individuals prepare for suitable roles. Job-ready individuals know what they can do well and are willing to learn where improvement is needed. This includes understanding your work style, communication preferences, and how you handle stress.\n\nWorkplace behavior is equally important. Showing respect, being polite, and maintaining a positive attitude influence how others perceive reliability. Even basic behaviors such as arriving on time, dressing appropriately, and listening carefully play a major role in job success. Your daily habits at work reflect your professionalism.\n\nJob readiness also includes adaptability. Work environments change, tasks evolve, and challenges arise. Being flexible and open to feedback helps individuals adjust and grow. The modern workplace requires workers who can learn new skills quickly and embrace change positively.\n\nPractical skills are part of job readiness too. These include basic computer literacy, reading comprehension, basic math, and the ability to follow written and verbal instructions. Many jobs require these fundamental abilities as a baseline.\n\nEmotional intelligence plays a crucial role in job readiness. Understanding your emotions, managing stress, and recognizing how your behavior affects others helps create positive workplace relationships. Employers value workers who can stay calm under pressure and work well with diverse teams.\n\nIn summary, job readiness is the foundation for employment success. It combines skills, behavior, mindset, and responsibility to help individuals enter the workforce confidently and professionally.", images: [{ image_id: "M1L1_IMG1", prompt: "HD professional illustration of diverse people preparing for work in a modern environment, clean flat style, NO TEXT IN IMAGE" }, { image_id: "M1L1_IMG2", prompt: "HD vector illustration showing professional readiness and confidence before starting work, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L2", title: "Understanding Employer Expectations", body: "Employers expect more than task completion. They value reliability, honesty, teamwork, and communication. Understanding these expectations helps job seekers align behavior with workplace standards.\n\nReliability is one of the most valued qualities. Employers expect workers to arrive on time, complete assigned tasks, and follow schedules. Being dependable builds trust over time. When you consistently meet expectations, you become someone supervisors can count on for important responsibilities.\n\nCommunication expectations include listening carefully, asking questions when unsure, and responding respectfully. Clear communication prevents mistakes and misunderstandings. This includes both verbal communication and written communication such as emails and reports.\n\nEmployers also expect accountability. Taking responsibility for mistakes and learning from them demonstrates maturity and professionalism. When errors occur, admitting them quickly and proposing solutions shows character and integrity.\n\nWorkplace rules and policies must be followed. These rules exist to ensure safety, fairness, and efficiency. Understanding company policies about attendance, dress code, technology use, and workplace conduct is essential for success.\n\nTeamwork is expected in most workplaces. Employers want workers who can collaborate effectively, share ideas constructively, and support their colleagues. Being a team player means putting group success alongside personal achievement.\n\nProfessional growth is increasingly expected. Employers appreciate workers who seek to improve their skills, take initiative in learning new technologies, and adapt to changing job requirements. Showing a growth mindset demonstrates long-term value.\n\nRespecting diversity and inclusion is a modern workplace expectation. Employers expect workers to treat all colleagues with respect regardless of background, culture, age, or other differences. An inclusive attitude contributes to a positive work environment.\n\nIn summary, understanding employer expectations helps individuals adapt quickly and perform successfully in any role.", images: [{ image_id: "M1L2_IMG1", prompt: "HD professional illustration of an employer explaining expectations to employees, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L2_IMG2", prompt: "HD vector illustration showing teamwork and responsibility at work, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L3", title: "Professional Attitude and Mindset", body: "A professional attitude influences success in the workplace. It reflects how individuals approach tasks, challenges, and interactions with others. Your mindset shapes not only how you work but also how others perceive your potential.\n\nA positive mindset helps individuals handle pressure and setbacks. Challenges are part of every job, and responding calmly shows maturity. When problems arise, focusing on solutions rather than blame demonstrates professionalism and leadership potential.\n\nRespectful behavior builds strong working relationships. Treating colleagues and supervisors with courtesy creates a supportive environment. This includes using polite language, acknowledging others' contributions, and being considerate of different work styles.\n\nWillingness to learn is another key aspect. Job-ready individuals are open to feedback and continuous improvement. They view constructive criticism as an opportunity to grow rather than a personal attack. This growth mindset is highly valued by employers.\n\nPersistence is essential for professional success. Many tasks require effort over time, and giving up easily shows lack of commitment. Professional individuals continue working toward goals even when progress is slow or obstacles appear.\n\nSelf-motivation drives consistent performance. While supervisors provide direction, professional workers take initiative without constant prompting. They identify what needs to be done and take action proactively.\n\nMaintaining professional boundaries helps preserve workplace harmony. This includes keeping personal issues separate from work, avoiding gossip, and respecting others' privacy. Professional boundaries protect both your reputation and workplace relationships.\n\nA service-oriented attitude enhances professional success. Whether serving customers, colleagues, or supervisors, focusing on how you can help others creates value and builds positive reputation.\n\nIn summary, a professional mindset supports growth, cooperation, and long-term success.", images: [{ image_id: "M1L3_IMG1", prompt: "HD professional illustration of a confident worker with positive attitude, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L3_IMG2", prompt: "HD vector illustration showing calm problem-solving at work, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L4", title: "Workplace Behavior and Etiquette", body: "Workplace behavior refers to how individuals act in professional environments. Etiquette includes manners, communication style, and respect for rules. Good workplace behavior creates a positive atmosphere that benefits everyone.\n\nProfessional etiquette includes greeting others politely, listening without interruption, and maintaining appropriate boundaries. Simple courtesies like saying 'please' and 'thank you' show respect and build positive relationships with colleagues.\n\nBehavior also includes managing emotions. Staying calm and respectful during disagreements prevents conflict escalation. Even when frustrated, maintaining composure demonstrates maturity and professionalism.\n\nRespecting personal space and property is basic workplace etiquette. This includes not using others' belongings without permission, keeping shared spaces clean, and being mindful of noise levels that might disturb colleagues.\n\nMeeting etiquette involves arriving on time, being prepared with necessary materials, listening actively to others, and contributing constructively. Avoiding distractions like checking your phone during meetings shows respect for others' time.\n\nEmail and digital communication etiquette includes using professional language, responding promptly, using appropriate subject lines, and checking for errors before sending. Digital communications represent you professionally and permanently.\n\nDress code compliance shows respect for workplace standards. Even in casual environments, maintaining appropriate appearance demonstrates professionalism. Understanding what is appropriate for different situations shows good judgment.\n\nLunchroom and break area etiquette includes cleaning up after yourself, respecting others' food, and using shared spaces considerately. These small behaviors reflect your overall professionalism.\n\nIn summary, good workplace behavior supports teamwork, trust, and productivity.", images: [{ image_id: "M1L4_IMG1", prompt: "HD professional illustration of respectful workplace interaction, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L4_IMG2", prompt: "HD vector illustration showing polite communication in an office setting, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L5", title: "Time Management Basics", body: "Time management is a critical job readiness skill. Employers expect tasks to be completed within given timeframes. Effective time management helps you accomplish more while reducing stress and improving work quality.\n\nManaging time involves planning, prioritizing tasks, and avoiding distractions. Starting each day or week with a clear plan of what needs to be accomplished helps focus efforts on what matters most.\n\nPrioritization is the key to effective time management. Not all tasks are equally important. Learning to identify urgent and important tasks versus those that can wait helps allocate time wisely. The ability to prioritize shows good judgment.\n\nAvoiding procrastination improves productivity. Delaying difficult tasks creates stress and risks missed deadlines. Breaking large tasks into smaller steps makes them more manageable and helps maintain momentum.\n\nManaging distractions is increasingly important in modern workplaces. This includes limiting social media use, managing email efficiently, and creating focused work periods. Learning to say no to non-essential interruptions protects your productive time.\n\nUsing tools for time management helps maintain organization. Calendars, to-do lists, and scheduling apps can help track commitments and deadlines. Finding tools that work for your style improves consistency.\n\nBuilding buffer time into schedules prevents stress from unexpected delays. Realistic time estimates account for potential interruptions and the natural variation in how long tasks take to complete.\n\nConsistent time management improves productivity and reduces stress. Workers who manage time well are more reliable, produce better work, and experience less workplace anxiety.\n\nIn summary, managing time effectively supports reliability and performance.", images: [{ image_id: "M1L5_IMG1", prompt: "HD professional illustration of organized work schedule planning, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L5_IMG2", prompt: "HD vector illustration showing focused task management, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L6", title: "Responsibility and Accountability at Work", body: "Responsibility means taking ownership of tasks and actions. Accountability involves accepting outcomes and learning from mistakes. Together, these qualities build trust and credibility in the workplace.\n\nEmployers value workers who can be trusted to complete tasks independently. When given a task, responsible workers follow through without needing constant reminders or supervision. They take pride in their work and ensure quality results.\n\nOwning mistakes is part of accountability. Everyone makes errors, but how you respond matters. Admitting mistakes promptly, learning from them, and taking steps to prevent recurrence shows maturity and integrity.\n\nMeeting deadlines consistently demonstrates responsibility. When you commit to completing something by a certain time, following through builds trust. If delays are unavoidable, communicating early shows respect for others' planning.\n\nFollowing through on commitments extends beyond task completion. It includes attending scheduled meetings, responding to communications promptly, and keeping promises made to colleagues and supervisors.\n\nTaking initiative shows high-level responsibility. Seeing what needs to be done and acting without being asked demonstrates ownership of your role. This proactive approach is valued for career advancement.\n\nAccountability includes accepting feedback gracefully. When others point out areas for improvement, receiving this input professionally and making genuine efforts to improve shows accountability for your professional development.\n\nBeing reliable in small things builds trust for larger responsibilities. Consistently handling routine tasks well shows you can be trusted with more significant assignments over time.\n\nIn summary, responsibility builds credibility and career growth.", images: [{ image_id: "M1L6_IMG1", prompt: "HD professional illustration of an employee responsibly completing tasks, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L6_IMG2", prompt: "HD vector illustration showing accountability in a work environment, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L7", title: "Following Instructions Correctly", body: "Following instructions accurately ensures quality work and safety. Misunderstanding instructions can cause errors, delays, and even safety hazards. Developing strong instruction-following skills is essential for job success.\n\nListening carefully when receiving instructions is the first step. Give full attention to the person speaking, avoid interrupting, and focus on understanding the complete message. Taking notes helps capture important details.\n\nClarifying instructions and confirming understanding are professional habits. Asking questions when something is unclear prevents mistakes. Repeating back key points confirms mutual understanding before beginning work.\n\nReading written instructions thoroughly before starting helps prevent errors. This includes manuals, procedures, emails, and any other written guidance. Scanning quickly may cause you to miss important steps or warnings.\n\nFollowing steps in the correct order matters for many tasks. Some processes require specific sequences for safety or quality reasons. Skipping steps or changing order without authorization can create problems.\n\nAsking for help when stuck is better than guessing. If you encounter something unexpected or confusing, seeking guidance prevents mistakes from compounding. Knowing when to ask shows good judgment, not weakness.\n\nDocumenting your understanding in writing helps prevent miscommunication. For complex instructions, writing down your understanding and confirming it with the instructor ensures alignment.\n\nFollowing safety-related instructions is particularly critical. Ignoring safety procedures can result in injury to yourself or others. Always treat safety instructions with the highest priority.\n\nIn summary, instruction-following supports efficiency and trust.", images: [{ image_id: "M1L7_IMG1", prompt: "HD professional illustration of a worker listening carefully to instructions, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L7_IMG2", prompt: "HD vector illustration showing clear communication between supervisor and worker, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L8", title: "Adaptability in the Workplace", body: "Adaptability allows workers to adjust to change. Tasks, schedules, and expectations can shift due to business needs, technology changes, or market conditions. Workers who embrace change rather than resist it thrive in modern workplaces.\n\nFlexible individuals handle change calmly and learn quickly. When procedures change, they focus on understanding the new approach rather than complaining about the old way. This positive attitude makes transitions smoother.\n\nLearning new skills is part of workplace adaptability. As technology evolves and job requirements change, workers must continuously develop new capabilities. Viewing learning as an ongoing journey rather than a burden helps maintain relevance.\n\nAdjusting to different work environments may be necessary. This could include working with different teams, adapting to new supervision styles, or even changing physical work locations. Flexibility in these situations shows professionalism.\n\nHandling unexpected challenges demonstrates adaptability. When plans change suddenly or problems arise, staying calm and problem-solving shows resilience. Employers value workers who remain productive despite uncertainty.\n\nBeing open to feedback and changing behavior accordingly is adaptive. When supervisors or colleagues suggest improvements, implementing changes shows you can grow. Rigidity in behavior limits career advancement.\n\nEmbracing new technologies is increasingly important. Digital tools and systems evolve constantly. Workers who approach new technology with curiosity rather than fear adapt more successfully.\n\nWorking with diverse colleagues requires social adaptability. Different people have different communication styles, cultural backgrounds, and work preferences. Adjusting your approach to work effectively with various colleagues shows maturity.\n\nIn summary, adaptability improves long-term employability.", images: [{ image_id: "M1L8_IMG1", prompt: "HD professional illustration of a worker adapting to new tasks, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L8_IMG2", prompt: "HD vector illustration showing workplace flexibility, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L9", title: "Personal Presentation and Appearance", body: "Personal presentation influences first impressions. Clean, appropriate appearance shows respect for the workplace, colleagues, and yourself. How you present yourself visually communicates professionalism before you even speak.\n\nDress standards vary, but neatness and hygiene are always expected. Some workplaces require formal business attire while others are more casual. Understanding your workplace's expectations and meeting them shows awareness and respect.\n\nGood grooming basics include clean hair, trimmed nails, appropriate use of fragrances, and overall tidiness. These details may seem minor but contribute significantly to professional appearance. Employers notice attention to personal care.\n\nClothing should be clean, well-fitted, and appropriate for the work environment. Wrinkled, stained, or damaged clothing detracts from professional appearance regardless of the dress code level. Taking care of your work clothes shows you take your job seriously.\n\nUnderstanding context helps you dress appropriately for different situations. Client meetings, casual office days, and physical labor all have different appropriate attire. Showing good judgment about context demonstrates professional awareness.\n\nPersonal hygiene directly affects workplace relationships. Body odor, bad breath, or other hygiene issues can make colleagues uncomfortable and damage professional relationships. Maintaining good hygiene is a basic workplace requirement.\n\nAccessories and jewelry should be appropriate for your work environment. Excessive or distracting accessories may not be suitable for professional settings. When in doubt, keep accessories simple and understated.\n\nYour posture and body language are part of your presentation. Standing and sitting with good posture projects confidence and professionalism. Slouching or appearing disengaged creates negative impressions.\n\nIn summary, presentation supports professionalism and confidence.", images: [{ image_id: "M1L9_IMG1", prompt: "HD professional illustration of well-presented workers in different job roles, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L9_IMG2", prompt: "HD vector illustration showing professional grooming and appearance, NO TEXT IN IMAGE" }] },
      { lesson_id: "M1L10", title: "Job Readiness Practice and Reflection", body: "Practicing job readiness skills daily helps turn knowledge into habit. Reflection allows individuals to improve continuously. Consistent practice and honest self-assessment accelerate professional development.\n\nReviewing experiences strengthens confidence and awareness. After completing tasks or interactions, taking time to think about what went well and what could improve builds skills faster than passive experience alone.\n\nSetting specific practice goals helps focus improvement efforts. Rather than vague intentions to 'be more professional,' specific goals like 'arrive 10 minutes early every day this week' create measurable targets.\n\nSeeking feedback from others provides valuable perspective. Supervisors, mentors, and colleagues can offer insights about your strengths and areas for improvement that you might not see yourself. Actively requesting feedback shows commitment to growth.\n\nKeeping a work journal helps track progress and patterns. Recording daily experiences, challenges, and learnings creates a valuable resource for reflection. Patterns become visible over time that might otherwise go unnoticed.\n\nPracticing difficult situations in low-stakes settings builds confidence. Role-playing challenging conversations, rehearsing presentations, or simulating work scenarios helps prepare for real situations.\n\nLearning from others' examples accelerates development. Observing how skilled colleagues handle situations, asking questions about their approaches, and modeling effective behaviors provides practical guidance.\n\nCelebrating progress, even small wins, maintains motivation. Recognizing improvements in your job readiness skills encourages continued effort. Acknowledging growth builds confidence for facing new challenges.\n\nCreating an action plan for continued development ensures progress doesn't stop. Identifying next steps for improvement and scheduling time for practice keeps professional growth on track.\n\nIn summary, practice and reflection prepare individuals for successful employment.", images: [{ image_id: "M1L10_IMG1", prompt: "HD professional illustration of a person reflecting on career goals, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M1L10_IMG2", prompt: "HD vector illustration showing self-reflection and growth, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M2",
    title: "Self-Assessment, Career Goals, and Job Planning",
    lessons: [
      { lesson_id: "M2L1", title: "Understanding Personal Strengths and Skills", body: "Understanding personal strengths and skills is a key step in job readiness. Every individual has abilities that can be valuable in the workplace. Identifying these strengths helps job seekers choose suitable roles and present themselves confidently to potential employers.\n\nPersonal strengths may include reliability, communication, organization, problem-solving, or physical abilities. Skills may come from previous work, education, daily responsibilities, or personal experiences. Even activities outside formal employment—such as caring for family members, volunteering, or managing household tasks—develop transferable skills.\n\nSelf-assessment involves reflecting on tasks that feel comfortable and areas where confidence is high. It also includes recognizing tasks that require improvement. Honest self-assessment supports realistic job planning and helps avoid pursuing roles that don't match your abilities.\n\nThere are different types of strengths to consider. Hard skills are specific, teachable abilities like computer programs, driving, or operating equipment. Soft skills are personal qualities like teamwork, patience, or adaptability. Both types are valuable to employers.\n\nUnderstanding strengths helps individuals focus on opportunities where they are most likely to succeed. It also helps identify skills that may need further development before applying for certain positions.\n\nAsking others for input can provide valuable perspective on your strengths. Friends, family members, or former supervisors may see abilities you overlook. Their observations can reveal patterns in what you do well.\n\nDocumenting your strengths creates a resource for job applications and interviews. Having specific examples of how you've demonstrated each strength makes your claims credible and memorable to employers.\n\nIn summary, recognizing personal strengths and skills builds confidence and supports better career decisions.", images: [{ image_id: "M2L1_IMG1", prompt: "HD professional illustration of a person reflecting on personal strengths and abilities, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L1_IMG2", prompt: "HD vector illustration showing skill identification and self-awareness, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L2", title: "Identifying Areas for Improvement", body: "Identifying areas for improvement is an important part of professional growth. Everyone has skills that can be strengthened over time. Recognizing these areas allows individuals to prepare better for employment and career advancement.\n\nAreas for improvement may include communication, time management, confidence, or technical skills. Acknowledging these areas does not indicate failure but shows readiness to learn. Employers value self-awareness and willingness to grow.\n\nHonest self-reflection is essential for identifying improvement areas. Think about tasks that feel challenging, situations where you've struggled, or feedback you've received. These provide clues about development needs.\n\nPrioritizing improvement areas helps focus effort effectively. You cannot improve everything at once. Identify which areas are most important for your career goals and address those first.\n\nSetting improvement goals helps individuals focus efforts effectively. Goals should be specific, measurable, and time-bound. For example, 'improve typing speed to 40 words per minute within three months' is more actionable than 'get better at computers.'\n\nFinding resources for improvement takes initiative. This might include online courses, books, practice exercises, or seeking mentorship. Many free resources exist for common skill development needs.\n\nTracking progress on improvement goals maintains motivation. Regular check-ins on your development help you see growth and adjust approaches that aren't working.\n\nSmall, consistent improvements lead to long-term success. Major skill development happens gradually through regular practice rather than occasional intense effort.\n\nIn summary, identifying improvement areas supports learning, growth, and job readiness.", images: [{ image_id: "M2L2_IMG1", prompt: "HD professional illustration of a person planning self-improvement steps, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L2_IMG2", prompt: "HD vector illustration showing skill development planning, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L3", title: "Exploring Career Interests", body: "Exploring career interests helps individuals choose work that matches preferences and abilities. Understanding what type of work feels meaningful increases job satisfaction and long-term career success.\n\nCareer interests may relate to working with people, hands-on tasks, organization, or creative activities. Some people prefer working independently while others thrive in team environments. Reflecting on past experiences helps identify these preferences.\n\nConsider what activities make time pass quickly because you're engaged. These flow experiences often indicate genuine interest. Similarly, notice what topics you choose to learn about voluntarily—these suggest natural curiosity.\n\nDifferent work environments suit different personalities. Some people prefer fast-paced, changing environments while others prefer predictable routines. Understanding your preferences helps target suitable opportunities.\n\nResearching different career paths expands awareness of possibilities. Many jobs exist that you may not know about. Informational interviews with people in various roles can provide insights into what work is really like.\n\nExploring options does not require immediate decisions. Learning about different roles builds awareness and helps refine preferences over time. Career exploration is an ongoing process, not a one-time event.\n\nTemporary or part-time work in different fields provides real experience. Trying different types of work—even in volunteer or informal settings—helps clarify what you enjoy and what you'd prefer to avoid.\n\nBalancing interests with practical considerations is important. While pursuing work you enjoy is valuable, also consider job availability, earning potential, and lifestyle factors in your exploration.\n\nIn summary, exploring interests supports informed and confident career choices.", images: [{ image_id: "M2L3_IMG1", prompt: "HD professional illustration of a person exploring different career paths, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L3_IMG2", prompt: "HD vector illustration showing career exploration concepts, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L4", title: "Setting Realistic Career Goals", body: "Setting realistic career goals provides direction and motivation. Goals should match skills, interests, and current circumstances. Well-defined goals transform vague aspirations into actionable plans.\n\nShort-term goals may include getting an entry-level job, completing a training program, or building specific skills. These goals can typically be achieved within months to a year. They provide stepping stones toward larger objectives.\n\nLong-term goals may involve career advancement, reaching a certain income level, or transitioning to a desired role. These goals might take several years to achieve and require multiple short-term goals along the way.\n\nRealistic goals balance ambition with practicality. While stretching yourself is valuable, goals that are impossible to achieve can lead to frustration. Consider your current situation and available resources when goal-setting.\n\nSMART goals are Specific, Measurable, Achievable, Relevant, and Time-bound. This framework helps create goals that are clear and actionable rather than vague wishes.\n\nWriting down goals increases commitment and accountability. Documented goals can be reviewed regularly and adjusted as circumstances change. Keeping goals visible reminds you of your direction.\n\nFlexibility in goal-setting allows adaptation to changing circumstances. While persistence matters, rigidly pursuing goals that no longer make sense wastes effort. Regular goal review ensures continued relevance.\n\nClear goals help individuals stay focused during job searching. When you know what you're working toward, decisions about opportunities become easier. Goals provide criteria for evaluation.\n\nIn summary, realistic goals guide career planning and progress.", images: [{ image_id: "M2L4_IMG1", prompt: "HD professional illustration of a person setting career goals, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L4_IMG2", prompt: "HD vector illustration showing goal-setting and planning, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L5", title: "Understanding Entry-Level Job Opportunities", body: "Entry-level jobs provide opportunities to gain experience and build work habits. These roles often focus on basic skills and learning rather than extensive prior experience. They serve as foundations for career development.\n\nEntry-level positions exist in nearly every industry. Retail, hospitality, healthcare support, administrative roles, and skilled trades all offer starting positions. Understanding the range of options helps identify suitable opportunities.\n\nUnderstanding entry-level expectations helps job seekers prepare realistically. These positions typically involve learning company processes, following established procedures, and demonstrating reliability. Entry-level workers prove themselves through consistent performance.\n\nWillingness to learn is highly valued in entry-level hiring. Employers often prefer candidates with positive attitudes and learning orientation over those with more experience but less adaptability. Demonstrate eagerness to develop.\n\nEntry-level positions may involve tasks that seem basic or repetitive. These responsibilities build foundational skills and demonstrate work ethic. Excellence in basic tasks often leads to increased responsibility.\n\nStarting wages for entry-level positions may be modest. Understanding that compensation typically increases with experience and demonstrated value helps maintain realistic expectations.\n\nMany successful professionals began in entry-level roles and advanced through dedication and skill development. Entry positions are starting points, not destinations. Viewing them as learning opportunities changes perspective.\n\nNetworking and relationship-building in entry-level roles creates advancement opportunities. The connections made early in your career can support growth for years to come.\n\nIn summary, entry-level roles support skill development and career entry.", images: [{ image_id: "M2L5_IMG1", prompt: "HD professional illustration of a beginner starting a new job role, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L5_IMG2", prompt: "HD vector illustration showing workplace learning for beginners, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L6", title: "Understanding Job Requirements", body: "Job requirements outline skills, responsibilities, and expectations. Understanding them helps job seekers prepare effectively and determine suitable opportunities. Careful analysis of requirements improves application success.\n\nReading job descriptions carefully prevents misunderstandings. Job postings contain information about required qualifications, preferred experience, responsibilities, and work conditions. Take time to understand each element.\n\nDistinguish between required and preferred qualifications. Required qualifications are necessary for the role while preferred qualifications are desirable but not essential. Many successful candidates don't meet every preferred qualification.\n\nMatching skills to requirements improves application success. When you can demonstrate relevant abilities for stated requirements, your candidacy strengthens. Prepare specific examples that show your qualifications.\n\nResearching employers helps understand unstated requirements. Company culture, values, and work style influence what they truly seek. Reading company information, reviews, and news provides context beyond job postings.\n\nUnderstanding industry-standard requirements helps with preparation. Many fields have common qualifications or certifications. Knowing these in advance allows proactive skill development.\n\nJob requirements evolve with technology and market changes. Skills that were optional years ago may now be expected. Staying current with industry trends helps anticipate future requirements.\n\nAsk questions about requirements during interviews to clarify expectations. This demonstrates thoughtfulness and ensures you understand the role fully before making decisions.\n\nIn summary, understanding requirements supports better job matching.", images: [{ image_id: "M2L6_IMG1", prompt: "HD professional illustration of a person reviewing job requirements, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L6_IMG2", prompt: "HD vector illustration showing job description analysis, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L7", title: "Planning a Job Search Strategy", body: "A job search strategy helps organize efforts and stay motivated. Planning reduces stress and increases efficiency. A systematic approach improves outcomes compared to random searching.\n\nStrategies may include identifying job sources, setting schedules, and tracking applications. Treating job searching as a structured activity with regular hours and defined tasks maintains momentum.\n\nIdentify multiple job search channels for best results. Online job boards, company websites, networking, staffing agencies, and local job centers all offer opportunities. Diversifying sources increases chances of success.\n\nSet specific, measurable job search goals. This might include applying to a certain number of positions weekly, making networking contacts, or attending job fairs. Goals maintain accountability and progress.\n\nTracking applications prevents confusion and supports follow-up. Record where you've applied, when, contact information, and status. Organization demonstrates professionalism and prevents duplicate applications.\n\nPrepare application materials in advance to respond quickly to opportunities. Having updated resumes, reference lists, and cover letter templates ready enables efficient applications.\n\nSchedule regular job search activities to maintain consistency. Sporadic efforts produce sporadic results. Consistent, focused searching is more effective than occasional intensive sessions.\n\nBalance persistence with self-care during job searching. Extended searches can be discouraging. Building in breaks, celebrating small wins, and maintaining perspective supports mental health.\n\nIn summary, planning supports consistent and focused job searching.", images: [{ image_id: "M2L7_IMG1", prompt: "HD professional illustration of a person planning a job search, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L7_IMG2", prompt: "HD vector illustration showing organized job search planning, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L8", title: "Using Feedback to Improve Career Direction", body: "Feedback helps individuals understand performance and improve direction. Feedback may come from mentors, supervisors, peers, or even interview experiences. Learning from input accelerates professional development.\n\nAccepting feedback professionally supports growth. Even difficult feedback contains valuable information. Responding defensively wastes learning opportunities and damages relationships with those trying to help.\n\nSeek feedback proactively rather than waiting for it to be offered. Asking trusted contacts for honest input demonstrates commitment to improvement. Specific questions generate more useful responses.\n\nDifferent perspectives offer complementary insights. Feedback from supervisors, colleagues, customers, and mentors each reveals different aspects of your professional presence. Gathering diverse input provides a complete picture.\n\nLook for patterns in feedback received over time. If multiple people mention similar areas, these deserve attention. Consistent feedback indicates genuine development opportunities.\n\nFeedback from unsuccessful job applications or interviews, when available, provides valuable learning. Understanding why you weren't selected helps improve future applications. Some employers provide feedback upon request.\n\nImplementing feedback demonstrates learning orientation. When you receive suggestions and visibly work on them, it builds credibility and shows you value input. This attracts continued support and guidance.\n\nProcessing difficult feedback may take time. It's okay to feel disappointed initially. The key is moving from reaction to reflection and eventually to action.\n\nIn summary, feedback strengthens career planning.", images: [{ image_id: "M2L8_IMG1", prompt: "HD professional illustration of constructive feedback discussion, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L8_IMG2", prompt: "HD vector illustration showing learning from feedback, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L9", title: "Balancing Expectations and Reality", body: "Balancing expectations and reality helps prevent disappointment. Understanding that growth takes time supports resilience. Realistic perspectives help navigate career development challenges.\n\nEntry roles may differ from long-term goals, but they provide experience. First jobs rarely match dream positions. Viewing early career stages as learning opportunities rather than destinations maintains motivation.\n\nCareer timelines often take longer than anticipated. Advancement, skill development, and goal achievement typically happen more gradually than expected. Patience and persistence are essential qualities.\n\nJob market conditions affect opportunity availability. Economic factors, industry trends, and geographic location influence what positions are available. Adjusting expectations to market reality prevents frustration.\n\nCompensation expectations should align with experience level and market rates. Researching typical pay for positions and locations prevents unrealistic salary expectations. Compensation often grows with demonstrated value.\n\nWork conditions may differ from expectations. Even good jobs involve some unpleasant tasks, difficult colleagues, or stressful periods. Perfect work environments exist only in imagination.\n\nSetbacks are normal parts of career development. Rejections, mistakes, and disappointments happen to everyone. How you respond to setbacks matters more than the setbacks themselves.\n\nBalancing high aspirations with practical realism optimizes outcomes. Dream big while taking practical steps forward. This combination maintains motivation while producing results.\n\nIn summary, realistic expectations support persistence.", images: [{ image_id: "M2L9_IMG1", prompt: "HD professional illustration of a person adjusting expectations realistically, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L9_IMG2", prompt: "HD vector illustration showing realistic career progression, NO TEXT IN IMAGE" }] },
      { lesson_id: "M2L10", title: "Career Planning Practice and Reflection", body: "Practicing career planning skills strengthens clarity and confidence. Reflection allows individuals to adjust goals and strategies. Regular practice builds proficiency in managing your own career development.\n\nCareer planning exercises help clarify direction. Activities like writing personal mission statements, creating vision boards, or conducting self-interviews develop clarity about what you want professionally.\n\nReviewing progress regularly maintains momentum. Monthly or quarterly reflection on career goals helps identify what's working and what needs adjustment. Regular review prevents drift from important objectives.\n\nDocumenting your career journey creates valuable records. Keeping notes on jobs held, skills developed, achievements, and lessons learned builds a resource for future applications and self-assessment.\n\nMentorship relationships support career planning. Finding experienced professionals who can offer guidance, share experiences, and provide feedback accelerates learning. Mentors provide perspective that's hard to gain alone.\n\nNetwork development is ongoing career planning work. Building relationships with professionals in your field, attending industry events, and maintaining connections supports long-term career options.\n\nStaying informed about industry trends helps with planning. Reading industry publications, following thought leaders, and paying attention to changes in your field supports strategic career decisions.\n\nCareer planning is lifelong work. Even experienced professionals continue refining their direction and developing new skills. Viewing career planning as an ongoing practice rather than a one-time activity supports sustained success.\n\nIn summary, practice and reflection support long-term career success.", images: [{ image_id: "M2L10_IMG1", prompt: "HD professional illustration of a person reflecting on career plans, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M2L10_IMG2", prompt: "HD vector illustration showing career reflection and planning, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M3",
    title: "Resume, Application, and Professional Profile Preparation",
    lessons: [
      { lesson_id: "M3L1", title: "Understanding the Purpose of a Resume", body: "A resume is a professional document that presents an individual's skills, experience, and suitability for a job. Its main purpose is to clearly show employers why the applicant is a good match for a role. A resume is often the first impression an employer receives, so clarity and accuracy are essential.\n\nA resume does not list everything a person has ever done. Instead, it highlights the most relevant information for the specific job being applied for. Employers usually review resumes quickly, so information must be easy to read and well organized.\n\nA strong resume focuses on abilities, reliability, and practical experience. This may include previous jobs, training, volunteering, or daily responsibilities that demonstrate useful skills.\n\nUnderstanding the purpose of a resume helps job seekers avoid common mistakes such as adding unnecessary details or using unclear language.\n\nIn summary, a resume is a focused professional summary designed to secure an interview opportunity.", images: [{ image_id: "M3L1_IMG1", prompt: "HD professional illustration of a person reviewing a resume document at a desk, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L1_IMG2", prompt: "HD vector illustration showing professional resume preparation concept, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L2", title: "Identifying Information to Include in a Resume", body: "Knowing what information to include in a resume ensures clarity and professionalism. Essential sections help employers quickly understand an applicant's background.\n\nCommon sections include personal details, work experience, skills, and education or training. Each section should be accurate and relevant to the job.\n\nWork experience does not need to be formal employment only. Volunteering, internships, caregiving, or household responsibilities can demonstrate valuable skills.\n\nSkills should be practical and job-related, such as communication, organization, teamwork, or time management.\n\nIn summary, including the right information helps employers assess suitability efficiently.", images: [{ image_id: "M3L2_IMG1", prompt: "HD professional illustration of a person organizing resume sections, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L2_IMG2", prompt: "HD vector illustration showing resume structure planning, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L3", title: "Writing Clear and Simple Resume Content", body: "Clear and simple language improves resume readability. Employers value resumes that are easy to understand and free from confusion.\n\nSentences should be short and direct. Responsibilities and achievements should be described using practical language.\n\nAvoid exaggeration. Honest descriptions build trust and credibility.\n\nUsing consistent formatting improves presentation.\n\nIn summary, simple and clear writing strengthens resume impact.", images: [{ image_id: "M3L3_IMG1", prompt: "HD professional illustration of a person typing a resume carefully, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L3_IMG2", prompt: "HD vector illustration showing clear resume writing process, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L4", title: "Presenting Skills and Experience Effectively", body: "Presenting skills and experience effectively helps employers see value quickly. Skills should match job requirements.\n\nExperience descriptions should focus on responsibilities and outcomes.\n\nUsing examples improves understanding.\n\nIn summary, effective presentation increases interview chances.", images: [{ image_id: "M3L4_IMG1", prompt: "HD professional illustration of a resume highlighting skills and experience visually, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L4_IMG2", prompt: "HD vector illustration showing skill matching to job roles, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L5", title: "Avoiding Common Resume Mistakes", body: "Common resume mistakes reduce effectiveness. These include spelling errors, unclear information, and unnecessary details.\n\nReviewing resumes carefully helps prevent mistakes.\n\nKeeping information accurate and relevant improves professionalism.\n\nIn summary, avoiding mistakes strengthens credibility.", images: [{ image_id: "M3L5_IMG1", prompt: "HD professional illustration of a person reviewing a resume for errors, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L5_IMG2", prompt: "HD vector illustration showing careful proofreading process, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L6", title: "Understanding Job Application Forms", body: "Job application forms collect information in a structured format. Understanding how to complete them correctly improves application success.\n\nForms require accuracy and consistency with resume details.\n\nReading instructions carefully prevents errors.\n\nIn summary, proper form completion supports professionalism.", images: [{ image_id: "M3L6_IMG1", prompt: "HD professional illustration of a person completing a job application form, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L6_IMG2", prompt: "HD vector illustration showing structured application process, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L7", title: "Providing Accurate and Honest Information", body: "Honesty in applications builds trust. Inaccurate information can cause problems later.\n\nAccurate details ensure credibility and alignment with employer expectations.\n\nIn summary, honesty supports long-term success.", images: [{ image_id: "M3L7_IMG1", prompt: "HD professional illustration of a person submitting an honest application, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L7_IMG2", prompt: "HD vector illustration showing trust and transparency in applications, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L8", title: "Creating a Professional Online Profile", body: "Online profiles support job searching by showcasing skills and experience. Profiles should be professional and accurate.\n\nConsistency with resumes is important.\n\nIn summary, professional online presence supports employment opportunities.", images: [{ image_id: "M3L8_IMG1", prompt: "HD professional illustration of a person creating an online professional profile, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L8_IMG2", prompt: "HD vector illustration showing digital professional presence, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L9", title: "Preparing Supporting Documents", body: "Supporting documents may include references or certificates. Preparing them in advance saves time.\n\nDocuments should be organized and accurate.\n\nIn summary, preparation supports smooth application processes.", images: [{ image_id: "M3L9_IMG1", prompt: "HD professional illustration of organized job documents on a desk, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L9_IMG2", prompt: "HD vector illustration showing document organization for job applications, NO TEXT IN IMAGE" }] },
      { lesson_id: "M3L10", title: "Resume and Application Practice and Reflection", body: "Practicing resume and application preparation improves confidence and quality. Reflection helps identify improvements.\n\nRegular review strengthens readiness.\n\nIn summary, practice and reflection enhance application success.", images: [{ image_id: "M3L10_IMG1", prompt: "HD professional illustration of a person reviewing completed job applications, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M3L10_IMG2", prompt: "HD vector illustration showing self-review and improvement, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M4",
    title: "Interview Preparation, Communication, and Performance",
    lessons: [
      { lesson_id: "M4L1", title: "Understanding the Purpose of Job Interviews", body: "A job interview is an opportunity for employers and candidates to learn about each other. Employers use interviews to assess skills, attitude, reliability, and communication. Candidates use interviews to understand job expectations and workplace culture.\n\nInterviews are not only about correct answers. Employers observe how candidates speak, listen, and respond under pressure. Confidence, honesty, and professionalism matter.\n\nUnderstanding the interview purpose helps candidates prepare calmly and realistically. Interviews are conversations, not tests.\n\nIn summary, interviews allow both sides to evaluate fit and expectations.", images: [{ image_id: "M4L1_IMG1", prompt: "HD professional illustration of a job interview conversation in a modern office, clean flat style, NO TEXT IN IMAGE" }, { image_id: "M4L1_IMG2", prompt: "HD vector illustration showing interview interaction between candidate and interviewer, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L2", title: "Preparing Mentally and Emotionally for Interviews", body: "Mental and emotional preparation helps candidates perform confidently during interviews. Nervousness is normal, but preparation reduces stress.\n\nUnderstanding the job role, reviewing personal experience, and practicing responses build confidence.\n\nPositive self-talk and calm breathing support emotional control.\n\nIn summary, mental preparation improves focus and confidence.", images: [{ image_id: "M4L2_IMG1", prompt: "HD professional illustration of a person preparing calmly before an interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L2_IMG2", prompt: "HD vector illustration showing confidence and calmness before interview, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L3", title: "Researching the Employer and Job Role", body: "Researching the employer and job role demonstrates interest and professionalism. Understanding company values and responsibilities helps candidates answer questions clearly.\n\nResearch may include learning about services, work environment, and expectations.\n\nIn summary, research supports informed and relevant interview responses.", images: [{ image_id: "M4L3_IMG1", prompt: "HD professional illustration of a person researching a company before interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L3_IMG2", prompt: "HD vector illustration showing job research preparation, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L4", title: "Common Interview Questions and How to Answer", body: "Interview questions often focus on experience, behavior, and attitude. Preparing structured answers improves clarity.\n\nAnswers should be honest, clear, and relevant. Examples help demonstrate skills.\n\nIn summary, preparation improves answer quality.", images: [{ image_id: "M4L4_IMG1", prompt: "HD professional illustration of a candidate responding confidently to interview questions, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L4_IMG2", prompt: "HD vector illustration showing question-and-answer interview flow, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L5", title: "Communicating Clearly and Confidently", body: "Clear communication is essential during interviews. Speaking clearly, listening carefully, and maintaining appropriate tone supports understanding.\n\nConfidence is shown through posture, eye contact, and calm speech.\n\nIn summary, effective communication strengthens interview performance.", images: [{ image_id: "M4L5_IMG1", prompt: "HD professional illustration of confident verbal communication during an interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L5_IMG2", prompt: "HD vector illustration showing confident communication skills, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L6", title: "Non-Verbal Communication in Interviews", body: "Non-verbal communication includes body language, facial expressions, and posture. These signals influence impressions.\n\nPositive body language shows confidence and interest.\n\nIn summary, non-verbal cues support spoken communication.", images: [{ image_id: "M4L6_IMG1", prompt: "HD professional illustration of positive body language during an interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L6_IMG2", prompt: "HD vector illustration showing professional posture and gestures, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L7", title: "Handling Difficult Interview Questions", body: "Difficult questions may address gaps, weaknesses, or challenges. Handling them calmly demonstrates maturity.\n\nHonest, thoughtful responses show self-awareness.\n\nIn summary, calm handling builds credibility.", images: [{ image_id: "M4L7_IMG1", prompt: "HD professional illustration of a candidate calmly answering a difficult interview question, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L7_IMG2", prompt: "HD vector illustration showing problem-solving during interviews, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L8", title: "Asking Appropriate Questions to Employers", body: "Asking questions shows interest and engagement. Questions should relate to the role and work environment.\n\nAvoid questions about salary or benefits too early unless invited.\n\nIn summary, thoughtful questions leave positive impressions.", images: [{ image_id: "M4L8_IMG1", prompt: "HD professional illustration of a candidate asking thoughtful questions in an interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L8_IMG2", prompt: "HD vector illustration showing respectful interview dialogue, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L9", title: "Following Up After an Interview", body: "Following up after interviews shows professionalism and appreciation. Simple follow-up actions reinforce interest.\n\nRespect timing and communication methods.\n\nIn summary, follow-up supports professional image.", images: [{ image_id: "M4L9_IMG1", prompt: "HD professional illustration of a candidate following up after interview, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L9_IMG2", prompt: "HD vector illustration showing professional follow-up behavior, NO TEXT IN IMAGE" }] },
      { lesson_id: "M4L10", title: "Interview Practice and Self-Reflection", body: "Practicing interviews improves performance. Reflection helps identify strengths and improvement areas.\n\nMock interviews and feedback build confidence.\n\nIn summary, practice and reflection strengthen interview readiness.", images: [{ image_id: "M4L10_IMG1", prompt: "HD professional illustration of mock interview practice, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M4L10_IMG2", prompt: "HD vector illustration showing interview reflection and learning, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M5",
    title: "Workplace Success, Growth, and Long-Term Career Stability",
    lessons: [
      { lesson_id: "M5L1", title: "Understanding Workplace Culture", body: "Workplace culture refers to the shared values, behaviors, and expectations that shape how people work together. Understanding workplace culture helps new employees adjust quickly and avoid misunderstandings. Every organization has its own culture influenced by leadership style, team dynamics, and industry standards.\n\nCulture affects communication, decision-making, and daily interactions. Some workplaces value formal communication, while others are more relaxed. Observing how colleagues interact provides important clues.\n\nRespecting workplace culture means adapting behavior while maintaining professionalism. This includes following dress standards, communication norms, and work routines.\n\nIn summary, understanding workplace culture supports smoother integration and long-term success.", images: [{ image_id: "M5L1_IMG1", prompt: "HD professional illustration of employees working together in a positive workplace culture, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L1_IMG2", prompt: "HD vector illustration showing teamwork and shared values at work, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L2", title: "Building Positive Work Relationships", body: "Positive work relationships improve teamwork, communication, and job satisfaction. Strong relationships are built through respect, reliability, and cooperation.\n\nListening actively, offering help, and communicating politely support healthy interactions. Avoiding gossip and conflict builds trust.\n\nProfessional relationships do not require close friendships, but mutual respect is essential.\n\nIn summary, positive relationships contribute to a supportive and productive workplace.", images: [{ image_id: "M5L2_IMG1", prompt: "HD professional illustration of coworkers collaborating respectfully, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L2_IMG2", prompt: "HD vector illustration showing professional teamwork and cooperation, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L3", title: "Managing Workplace Challenges and Conflict", body: "Challenges and conflicts can arise in any workplace. Managing them professionally helps maintain productivity and respect.\n\nCommon challenges include miscommunication, workload pressure, and personality differences. Addressing issues calmly prevents escalation.\n\nSeeking guidance from supervisors when needed shows responsibility.\n\nIn summary, effective conflict management supports a healthy work environment.", images: [{ image_id: "M5L3_IMG1", prompt: "HD professional illustration of calm conflict resolution at work, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L3_IMG2", prompt: "HD vector illustration showing problem-solving in workplace situations, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L4", title: "Receiving Feedback and Performance Reviews", body: "Feedback helps employees understand performance and improve skills. Performance reviews provide structured feedback.\n\nReceiving feedback professionally involves listening, asking questions, and applying suggestions.\n\nViewing feedback as learning supports growth.\n\nIn summary, feedback improves performance and career development.", images: [{ image_id: "M5L4_IMG1", prompt: "HD professional illustration of a supervisor giving constructive feedback, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L4_IMG2", prompt: "HD vector illustration showing professional feedback discussion, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L5", title: "Maintaining Professional Ethics at Work", body: "Professional ethics guide responsible workplace behavior. Ethics include honesty, fairness, and respect.\n\nFollowing rules, protecting confidentiality, and acting responsibly support trust.\n\nIn summary, ethical behavior strengthens professional reputation.", images: [{ image_id: "M5L5_IMG1", prompt: "HD professional illustration of ethical decision-making at work, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L5_IMG2", prompt: "HD vector illustration showing integrity and responsibility in the workplace, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L6", title: "Time Management and Productivity at Work", body: "Managing time effectively improves productivity and reduces stress. Prioritizing tasks and staying organized supports efficiency.\n\nAvoiding distractions and planning ahead improves results.\n\nIn summary, time management supports consistent performance.", images: [{ image_id: "M5L6_IMG1", prompt: "HD professional illustration of an employee managing tasks efficiently, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L6_IMG2", prompt: "HD vector illustration showing organized workflow and productivity, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L7", title: "Continuous Learning and Skill Improvement", body: "Continuous learning helps employees stay relevant and improve performance. Learning may include training, practice, and feedback.\n\nImproving skills increases confidence and opportunity.\n\nIn summary, learning supports long-term career success.", images: [{ image_id: "M5L7_IMG1", prompt: "HD professional illustration of an employee learning new workplace skills, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L7_IMG2", prompt: "HD vector illustration showing professional development and growth, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L8", title: "Career Growth and Advancement Awareness", body: "Career growth involves gaining experience, responsibility, and new skills. Understanding growth opportunities helps employees plan.\n\nProgress may be gradual and requires patience.\n\nIn summary, awareness supports realistic career development.", images: [{ image_id: "M5L8_IMG1", prompt: "HD professional illustration of career progression over time, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L8_IMG2", prompt: "HD vector illustration showing upward career development path, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L9", title: "Maintaining Work-Life Balance", body: "Work-life balance supports physical and emotional health. Balancing work responsibilities with rest prevents burnout.\n\nSetting boundaries and managing time supports balance.\n\nIn summary, balance improves long-term job satisfaction.", images: [{ image_id: "M5L9_IMG1", prompt: "HD professional illustration of balanced work and personal life, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L9_IMG2", prompt: "HD vector illustration showing healthy daily routine balance, NO TEXT IN IMAGE" }] },
      { lesson_id: "M5L10", title: "Career Success Reflection and Course Completion", body: "Reflecting on learning helps individuals recognize progress and prepare for future goals. Course completion marks readiness to apply skills professionally.\n\nReviewing strengths and areas for improvement supports confidence.\n\nIn summary, reflection and commitment support long-term success.", images: [{ image_id: "M5L10_IMG1", prompt: "HD professional illustration of a person reflecting on career achievements, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M5L10_IMG2", prompt: "HD vector illustration showing course completion and professional readiness, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M6",
    title: "Workplace Communication, Teamwork, and Professional Conduct",
    lessons: [
      { lesson_id: "M6L1", title: "Understanding Workplace Communication", body: "Workplace communication is the process of sharing information, ideas, and instructions in a professional environment. Clear communication helps tasks get completed correctly, reduces misunderstandings, and builds trust among team members.\n\nCommunication can be verbal, written, or non-verbal. Verbal communication includes conversations, meetings, and phone calls. Written communication includes emails, messages, and reports. Non-verbal communication includes body language, facial expressions, and tone of voice.\n\nEffective workplace communication requires clarity. Messages should be simple, direct, and respectful. Speaking too quickly or using unclear language can cause confusion.\n\nListening is just as important as speaking. Active listening involves paying attention, avoiding interruptions, and confirming understanding.\n\nIn summary, strong workplace communication supports teamwork, accuracy, and professional relationships.", images: [{ image_id: "M6L1_IMG1", prompt: "HD professional illustration of coworkers communicating clearly in a workplace, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L1_IMG2", prompt: "HD vector illustration showing different types of workplace communication, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L2", title: "Active Listening Skills", body: "Active listening is a key professional skill that shows respect and improves understanding. It involves fully focusing on the speaker and responding appropriately.\n\nGood listening includes maintaining eye contact, nodding when appropriate, and avoiding distractions. Asking questions helps clarify information.\n\nActive listening reduces mistakes and improves cooperation.\n\nIn summary, listening carefully strengthens communication and teamwork.", images: [{ image_id: "M6L2_IMG1", prompt: "HD professional illustration of attentive listening during a work discussion, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L2_IMG2", prompt: "HD vector illustration showing focused listening behavior, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L3", title: "Communicating with Supervisors", body: "Communicating effectively with supervisors supports clear expectations and professional growth. Supervisors rely on accurate information to guide work.\n\nEmployees should ask questions when unsure and provide updates when tasks are completed or delayed.\n\nRespectful tone and honesty build trust.\n\nIn summary, clear supervisor communication supports success and accountability.", images: [{ image_id: "M6L3_IMG1", prompt: "HD professional illustration of an employee speaking respectfully with a supervisor, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L3_IMG2", prompt: "HD vector illustration showing professional supervisor communication, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L4", title: "Working Effectively in a Team", body: "Teamwork involves working with others to achieve shared goals. Effective teamwork requires cooperation, respect, and shared responsibility.\n\nTeam members should support one another, communicate clearly, and contribute fairly.\n\nUnderstanding roles helps avoid conflict.\n\nIn summary, teamwork improves productivity and workplace harmony.", images: [{ image_id: "M6L4_IMG1", prompt: "HD professional illustration of a diverse team collaborating at work, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L4_IMG2", prompt: "HD vector illustration showing teamwork and cooperation, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L5", title: "Handling Workplace Disagreements Professionally", body: "Disagreements can occur when people have different opinions or work styles. Handling them professionally prevents conflict escalation.\n\nRemaining calm, listening respectfully, and focusing on solutions helps resolve issues.\n\nIn summary, professional conflict handling supports a healthy work environment.", images: [{ image_id: "M6L5_IMG1", prompt: "HD professional illustration of calm workplace conflict discussion, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L5_IMG2", prompt: "HD vector illustration showing peaceful problem resolution, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L6", title: "Written Communication Basics", body: "Written communication includes emails, messages, and notes. Professional writing should be clear, polite, and accurate.\n\nUsing simple language and checking for errors improves clarity.\n\nIn summary, strong writing skills support professionalism.", images: [{ image_id: "M6L6_IMG1", prompt: "HD professional illustration of an employee writing a professional email, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L6_IMG2", prompt: "HD vector illustration showing clear written communication, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L7", title: "Professional Phone and Online Communication", body: "Phone and online communication require clear speech and professional tone. Speaking politely and listening carefully are essential.\n\nResponding promptly and respectfully supports trust.\n\nIn summary, digital communication skills support modern workplaces.", images: [{ image_id: "M6L7_IMG1", prompt: "HD professional illustration of professional phone communication at work, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L7_IMG2", prompt: "HD vector illustration showing online professional communication, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L8", title: "Respecting Diversity in the Workplace", body: "Workplaces often include people from different backgrounds. Respecting diversity supports inclusion and cooperation.\n\nTreating everyone fairly and respectfully improves teamwork.\n\nIn summary, diversity awareness supports positive work culture.", images: [{ image_id: "M6L8_IMG1", prompt: "HD professional illustration of diverse coworkers working together respectfully, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L8_IMG2", prompt: "HD vector illustration showing inclusive workplace environment, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L9", title: "Maintaining Professional Boundaries", body: "Professional boundaries help maintain respectful relationships. Boundaries define appropriate behavior and communication.\n\nAvoiding personal conflicts and respecting privacy supports professionalism.\n\nIn summary, boundaries protect work relationships.", images: [{ image_id: "M6L9_IMG1", prompt: "HD professional illustration of respectful workplace boundaries, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L9_IMG2", prompt: "HD vector illustration showing professional distance at work, NO TEXT IN IMAGE" }] },
      { lesson_id: "M6L10", title: "Communication and Teamwork Practice and Reflection", body: "Practicing communication and teamwork skills strengthens confidence. Reflection helps identify improvement areas.\n\nApplying feedback supports growth.\n\nIn summary, practice and reflection improve workplace effectiveness.", images: [{ image_id: "M6L10_IMG1", prompt: "HD professional illustration of team reflection meeting, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M6L10_IMG2", prompt: "HD vector illustration showing learning through teamwork reflection, NO TEXT IN IMAGE" }] }
    ]
  },
  {
    module_id: "M7",
    title: "Financial Awareness, Workplace Rights, and Long-Term Stability",
    lessons: [
      { lesson_id: "M7L1", title: "Understanding Workplace Rights and Responsibilities", body: "Understanding workplace rights and responsibilities helps employees protect themselves and act professionally. Every worker has rights related to fair treatment, safety, and respect. At the same time, employees have responsibilities to follow rules and perform duties honestly.\n\nWorkplace rights may include fair pay, safe working conditions, and freedom from discrimination. Responsibilities include following instructions, respecting others, and complying with workplace policies.\n\nKnowing both rights and responsibilities creates balance and confidence at work.\n\nIn summary, awareness of rights and responsibilities supports fairness and professionalism.", images: [{ image_id: "M7L1_IMG1", prompt: "HD professional illustration of employees working confidently knowing their rights, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L1_IMG2", prompt: "HD vector illustration showing balanced workplace rights and duties, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L2", title: "Understanding Employment Agreements", body: "Employment agreements outline job roles, responsibilities, and conditions. Understanding these agreements helps employees know what is expected.\n\nAgreements may include work hours, responsibilities, and conduct expectations. Reading agreements carefully prevents misunderstandings.\n\nIn summary, understanding agreements supports clarity and protection.", images: [{ image_id: "M7L2_IMG1", prompt: "HD professional illustration of a person reviewing an employment agreement, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L2_IMG2", prompt: "HD vector illustration showing clear employment terms understanding, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L3", title: "Basic Financial Awareness for Employees", body: "Financial awareness helps employees manage income responsibly. Understanding earnings, budgeting, and expenses supports stability.\n\nKnowing how to plan finances reduces stress and supports independence.\n\nIn summary, financial awareness strengthens personal security.", images: [{ image_id: "M7L3_IMG1", prompt: "HD professional illustration of a person planning personal finances responsibly, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L3_IMG2", prompt: "HD vector illustration showing income and expense management, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L4", title: "Understanding Pay, Hours, and Scheduling", body: "Understanding pay structures and schedules helps employees plan effectively. Awareness of work hours and compensation supports transparency.\n\nEmployees should track hours worked and understand payment timelines.\n\nIn summary, pay and scheduling knowledge supports fairness.", images: [{ image_id: "M7L4_IMG1", prompt: "HD professional illustration of an employee reviewing work schedule and pay details, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L4_IMG2", prompt: "HD vector illustration showing time and pay awareness, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L5", title: "Managing Personal Finances Responsibly", body: "Managing personal finances responsibly supports long-term stability. Budgeting, saving, and planning help meet obligations.\n\nResponsible financial habits reduce stress and support independence.\n\nIn summary, good financial management supports career stability.", images: [{ image_id: "M7L5_IMG1", prompt: "HD professional illustration of a person budgeting finances carefully, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L5_IMG2", prompt: "HD vector illustration showing responsible money management, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L6", title: "Understanding Workplace Safety Rights", body: "Employees have the right to a safe working environment. Understanding safety rights helps prevent injury.\n\nFollowing safety procedures and reporting hazards supports protection.\n\nIn summary, safety rights awareness supports well-being.", images: [{ image_id: "M7L6_IMG1", prompt: "HD professional illustration of a safe and compliant workplace environment, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L6_IMG2", prompt: "HD vector illustration showing workplace safety awareness, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L7", title: "Handling Workplace Issues and Seeking Support", body: "Workplace issues may arise and should be handled professionally. Knowing when and how to seek support is important.\n\nReporting concerns through proper channels helps resolve problems.\n\nIn summary, seeking support protects rights and well-being.", images: [{ image_id: "M7L7_IMG1", prompt: "HD professional illustration of an employee discussing a workplace concern responsibly, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L7_IMG2", prompt: "HD vector illustration showing professional issue reporting, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L8", title: "Long-Term Career Stability Planning", body: "Long-term stability involves consistent performance, financial responsibility, and growth planning.\n\nMaintaining skills and reliability supports continued employment.\n\nIn summary, planning supports career security.", images: [{ image_id: "M7L8_IMG1", prompt: "HD professional illustration of a person planning long-term career stability, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L8_IMG2", prompt: "HD vector illustration showing stable career growth path, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L9", title: "Building a Responsible Professional Lifestyle", body: "A responsible lifestyle supports work performance. Healthy routines, balance, and planning improve reliability.\n\nConsistency in habits supports career success.\n\nIn summary, responsible lifestyle choices support professional stability.", images: [{ image_id: "M7L9_IMG1", prompt: "HD professional illustration of a balanced professional lifestyle, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L9_IMG2", prompt: "HD vector illustration showing healthy work-life routines, NO TEXT IN IMAGE" }] },
      { lesson_id: "M7L10", title: "Career Stability Reflection and Course Extension Completion", body: "Reflecting on career stability skills helps individuals apply learning effectively. Completion of extended modules strengthens readiness.\n\nCommitment to responsible work behavior supports long-term success.\n\nIn summary, reflection reinforces stability and growth.", images: [{ image_id: "M7L10_IMG1", prompt: "HD professional illustration of a person reflecting on career stability and growth, modern flat style, NO TEXT IN IMAGE" }, { image_id: "M7L10_IMG2", prompt: "HD vector illustration showing professional reflection and confidence, NO TEXT IN IMAGE" }] }
    ]
  }
];

async function generateAndUploadImage(prompt: string, courseId: string, lessonId: string, imageIndex: number): Promise<string | null> {
  try {
    console.log(`🎨 Generating HD image for ${lessonId} image ${imageIndex + 1}...`);
    
    const response = await openai.images.generate({
      model: 'dall-e-3',
      prompt: prompt,
      size: '1024x1024',
      quality: 'hd',
      style: 'natural',
      n: 1
    });

    const imageUrl = response.data[0]?.url;
    if (!imageUrl) {
      console.error(`❌ No image URL returned for ${lessonId}`);
      return null;
    }

    console.log(`✅ Image generated, downloading and uploading to R2...`);

    const imageBuffer = await downloadImageToBuffer(imageUrl);
    
    const fileName = `${lessonId}_img${imageIndex + 1}_${crypto.randomBytes(4).toString('hex')}.png`;
    const folderPath = `uploads/courses/${courseId}/images`;
    
    const uploadResult = await r2Storage.uploadFile(
      imageBuffer,
      fileName,
      'image/png',
      folderPath
    );

    if (uploadResult.success && uploadResult.url) {
      console.log(`✅ Uploaded to R2: ${uploadResult.url}`);
      return uploadResult.url;
    } else {
      console.error(`❌ R2 upload failed: ${uploadResult.error}`);
      return null;
    }
  } catch (error: any) {
    console.error(`❌ Image generation/upload failed for ${lessonId}:`, error.message);
    return null;
  }
}

async function downloadImageToBuffer(url: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    https.get(url, (response) => {
      if (response.statusCode !== 200) {
        reject(new Error(`Failed to download image: ${response.statusCode}`));
        return;
      }

      const chunks: Buffer[] = [];
      response.on('data', (chunk) => chunks.push(chunk));
      response.on('end', () => resolve(Buffer.concat(chunks)));
      response.on('error', reject);
    }).on('error', reject);
  });
}

async function seedJobReadinessCourse() {
  console.log('🚀 Starting Job Readiness Course seeding...');
  
  const adminUser = await ensureAdminUser();
  if (!adminUser) {
    console.error('❌ Failed to get admin user');
    return;
  }

  let businessCategory = await db.select().from(courseCategories).where(eq(courseCategories.name, 'Business')).limit(1);
  
  if (businessCategory.length === 0) {
    const [newCategory] = await db.insert(courseCategories).values({
      name: 'Business',
      displayName: 'Business & Career Development',
      description: 'Courses about business, career development, and professional skills',
      color: 'green',
      isActive: true
    }).returning();
    businessCategory = [newCategory];
  }

  const categoryId = businessCategory[0].id;
  console.log(`📁 Using category: ${businessCategory[0].displayName} (${categoryId})`);

  const existingCourse = await db.select().from(courses).where(eq(courses.title, COURSE_TITLE)).limit(1);
  
  let courseId: string;
  
  if (existingCourse.length > 0) {
    console.log('📚 Course already exists, updating...');
    courseId = existingCourse[0].id;
    await db.update(courses).set({
      description: COURSE_STRUCTURE.description,
      learningObjectives: COURSE_STRUCTURE.learning_outcomes,
      categoryId: categoryId
    }).where(eq(courses.id, courseId));
  } else {
    console.log('📚 Creating new course...');
    const [newCourse] = await db.insert(courses).values({
      title: COURSE_TITLE,
      description: COURSE_STRUCTURE.description,
      thumbnailUrl: '',
      categoryId: categoryId,
      pricingType: 'free',
      difficulty: 'beginner',
      duration: 50,
      tags: ['Job Readiness', 'Career', 'Interview', 'Resume', 'Workplace', 'Professional Skills', 'Employment'],
      language: 'en',
      isFeatured: true,
      isPublished: true,
      publisherName: 'EduFiliova Career Academy',
      publisherBio: 'Expert educators helping you succeed in your career journey',
      learningObjectives: COURSE_STRUCTURE.learning_outcomes,
      certificationType: 'certificate',
      credits: 5,
      createdBy: adminUser.id
    }).returning();
    
    courseId = newCourse.id;
    console.log(`✅ Course created with ID: ${courseId}`);
  }

  console.log(`\n📦 Processing ${MODULES_DATA.length} modules with ${MODULES_DATA.reduce((acc, m) => acc + m.lessons.length, 0)} lessons...`);
  console.log(`🖼️ Will generate ${MODULES_DATA.reduce((acc, m) => acc + m.lessons.reduce((la, l) => la + l.images.length, 0), 0)} HD images\n`);

  let totalImagesGenerated = 0;
  let totalImagesFailed = 0;

  for (let moduleIndex = 0; moduleIndex < MODULES_DATA.length; moduleIndex++) {
    const moduleData = MODULES_DATA[moduleIndex];
    console.log(`\n📦 Processing Module ${moduleIndex + 1}/${MODULES_DATA.length}: ${moduleData.title}`);

    const existingModule = await db.select().from(modules)
      .where(eq(modules.courseId, courseId))
      .limit(100);
    
    const moduleExists = existingModule.find(m => m.title === moduleData.title);
    
    let moduleId: string;
    
    if (moduleExists) {
      moduleId = moduleExists.id;
      console.log(`  ✓ Module exists: ${moduleId}`);
    } else {
      const [newModule] = await db.insert(modules).values({
        courseId: courseId,
        title: moduleData.title,
        description: `Module ${moduleIndex + 1}: ${moduleData.title}`,
        orderIndex: moduleIndex,
        isPublished: true
      }).returning();
      moduleId = newModule.id;
      console.log(`  ✓ Created module: ${moduleId}`);
    }

    for (let lessonIndex = 0; lessonIndex < moduleData.lessons.length; lessonIndex++) {
      const lessonData = moduleData.lessons[lessonIndex];
      console.log(`  📖 Lesson ${lessonIndex + 1}/${moduleData.lessons.length}: ${lessonData.title}`);

      const existingLesson = await db.select().from(lessons)
        .where(eq(lessons.moduleId, moduleId))
        .limit(100);
      
      const lessonExists = existingLesson.find(l => l.title === lessonData.title);
      
      let lessonId: string;
      
      if (lessonExists) {
        lessonId = lessonExists.id;
        console.log(`    ✓ Lesson exists: ${lessonId}`);
      } else {
        const [newLesson] = await db.insert(lessons).values({
          moduleId: moduleId,
          title: lessonData.title,
          description: lessonData.body.substring(0, 200) + '...',
          orderIndex: lessonIndex,
          orderNum: lessonIndex + 1,
          contentType: 'reading_material',
          isPublished: true,
          duration: 10
        }).returning();
        lessonId = newLesson.id;
        console.log(`    ✓ Created lesson: ${lessonId}`);
      }

      const existingBlocks = await db.select().from(lessonContentBlocks)
        .where(eq(lessonContentBlocks.lessonId, lessonId));

      if (existingBlocks.length > 0) {
        console.log(`    ⏭️ Content blocks already exist, skipping...`);
        continue;
      }

      const imageUrls: string[] = [];
      for (let imgIndex = 0; imgIndex < lessonData.images.length; imgIndex++) {
        const imageData = lessonData.images[imgIndex];
        const imageUrl = await generateAndUploadImage(
          imageData.prompt,
          courseId,
          lessonData.lesson_id,
          imgIndex
        );
        
        if (imageUrl) {
          imageUrls.push(imageUrl);
          totalImagesGenerated++;
        } else {
          totalImagesFailed++;
        }
        
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      let blockOrder = 0;

      if (imageUrls.length > 0) {
        await db.insert(lessonContentBlocks).values({
          lessonId: lessonId,
          blockType: 'image',
          content: imageUrls[0],
          orderIndex: blockOrder++
        });
      }

      await db.insert(lessonContentBlocks).values({
        lessonId: lessonId,
        blockType: 'text',
        content: lessonData.body,
        orderIndex: blockOrder++
      });

      if (imageUrls.length > 1) {
        await db.insert(lessonContentBlocks).values({
          lessonId: lessonId,
          blockType: 'image',
          content: imageUrls[1],
          orderIndex: blockOrder++
        });
      }

      console.log(`    ✅ Added ${blockOrder} content blocks with ${imageUrls.length} images`);
    }
  }

  const courseThumbnailPrompt = "HD professional illustration of diverse people in business attire preparing for successful careers, showing job interviews, resume preparation, and workplace success, modern flat style, corporate blue and green colors, NO TEXT IN IMAGE";
  
  console.log('\n🖼️ Generating course thumbnail...');
  const thumbnailUrl = await generateAndUploadImage(courseThumbnailPrompt, courseId, 'thumbnail', 0);
  
  if (thumbnailUrl) {
    await db.update(courses).set({ thumbnailUrl: thumbnailUrl }).where(eq(courses.id, courseId));
    console.log(`✅ Course thumbnail updated: ${thumbnailUrl}`);
  }

  console.log('\n========================================');
  console.log('🎉 Job Readiness Course seeding complete!');
  console.log(`📚 Course ID: ${courseId}`);
  console.log(`📦 Modules: ${MODULES_DATA.length}`);
  console.log(`📖 Lessons: ${MODULES_DATA.reduce((acc, m) => acc + m.lessons.length, 0)}`);
  console.log(`🖼️ Images generated: ${totalImagesGenerated}`);
  console.log(`❌ Images failed: ${totalImagesFailed}`);
  console.log('========================================\n');
}

seedJobReadinessCourse()
  .then(() => {
    console.log('✅ Seeding completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  });
